import type { Metadata } from "next";
import { Fredoka } from "next/font/google";

import "./globals.css";

const fredoka = Fredoka({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ABBADI Garderie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={fredoka.className}>{children}</body>
    </html>
  );
}
